### ISSUE TITLE
Monoid.reduce has different signatures for objects and arrays

### ISSUE THREAD

**Issue by taras** [cowboyd/funcadelic.js#18]
Same monoid reduce will produce a different result for `[1, 2, 3, 4]` than `{ "1": 1, "2": 2, "3": 3, "4": 4 }`. This makes it inconvenient when trying to use the same monoid for both arrays and objects. I would expect to be able to use the same monoid for both without having to make special accommodation for both types. 

When reducing arrays, the append function for the array receives a value for `a` and `b`. Reducing objects, sends memo for `a` and `b`. This is caused by the difference in implementation of `foldl` for Arrays and Objects. 

I believe that both `foldl` for Arrays and Objects should send data of same shape to the folding function. It should be other value or memo, not either.

Failing test: https://github.com/taras/funcadelic.js/blob/monoid-signature-failing-test/tests/funcadelic-test.js#L67

**Comment by taras** [comment]
Yes, this would work nicely!

**Comment by taras** [comment]
We can close this issue and PR. I'll make another and reference this one.

**Comment by cowboyd** [comment]
Maybe we should try it out in libraries consuming it first, a-la `Monad`.

Also, I think that this highlights a weakness with error handling and messaging.
